# -*- coding: utf-8 -*-
"""
Dataset 79 okresných miest SR pre kominy-krby.sk lokálne podstránky.
Každý záznam: slug, mesto, lokativ (6. pád "v meste"), kraj, region (geo-blok),
neighbors (susedné okresné mestá pre interné linky), note (lokálny kontext).
"""

# region kód -> ľudský popis (klíma / palivá / typ zástavby) pre unikátny lokálny kontext
REGIONS = {
    "podunaj": "úrodná podunajská nížina s prevahou rovinatej zástavby, mierne zimy, rozšírené plynové aj kombinované kúrenie",
    "zahorie": "Záhorie a okolie Malých Karpát, kombinácia mestskej a vidieckej zástavby, časté krbové pece na drevo",
    "povazie": "údolie Váhu s množstvom starších rodinných domov a kotlov na tuhé palivo, vlhkejšie zimy",
    "ponitrie": "Ponitrie a tribečské podhorie, vinohradnícke obce so staršími murovanými komínmi",
    "turiec_orava_liptov": "horský región s tuhými zimami a intenzívnou vykurovacou sezónou, prevaha kúrenia na drevo a kombinovaných kotlov",
    "horehronie": "horehronský a podpolianský región s dlhou a chladnou vykurovacou sezónou, drevo ako hlavné palivo",
    "gemer_novohrad": "Gemer a Novohrad, vidiecka zástavba so starými murovanými komínmi náchylnými na dechtovanie",
    "spis": "Spiš a podtatranská oblasť s tvrdými zimami, kamenné a murované domy, vysoké nároky na ťah komína",
    "saris": "šarišský región, kopcovitý terén, kombinácia mestskej zástavby a horských obcí s kúrením na drevo",
    "zemplin": "Zemplín a východoslovenská nížina, teplejšie letá, časté kotly na tuhé palivo na vidieku",
    "kosice_okolie": "Košická kotlina a Abov, mestská aj prímestská zástavba, kombinácia plynu a tuhých palív",
}

# 79 okresných miest. neighbors = slugy 3-5 najbližších okresných miest.
CITIES = [
    # Bratislavský kraj
    {"slug":"bratislava","mesto":"Bratislava","lokativ":"Bratislave","kraj":"Bratislavský kraj","region":"podunaj",
     "neighbors":["malacky","pezinok","senec","trnava","dunajska-streda"],
     "note":"hlavné mesto s množstvom starších bytových domov v Starom Meste aj novostavieb v okrajových častiach"},
    {"slug":"malacky","mesto":"Malacky","lokativ":"Malackách","kraj":"Bratislavský kraj","region":"zahorie",
     "neighbors":["bratislava","pezinok","senica","skalica"],
     "note":"centrum Záhoria s prevahou rodinných domov a chalúp s pecami na drevo"},
    {"slug":"pezinok","mesto":"Pezinok","lokativ":"Pezinku","kraj":"Bratislavský kraj","region":"zahorie",
     "neighbors":["bratislava","senec","malacky","trnava"],
     "note":"vinohradnícke mesto pod Malými Karpatami so staršou aj novou zástavbou"},
    {"slug":"senec","mesto":"Senec","lokativ":"Senci","kraj":"Bratislavský kraj","region":"podunaj",
     "neighbors":["bratislava","pezinok","galanta","dunajska-streda"],
     "note":"rýchlo rastúce mesto pri Bratislave s množstvom novostavieb a krbov"},
    # Trnavský kraj
    {"slug":"trnava","mesto":"Trnava","lokativ":"Trnave","kraj":"Trnavský kraj","region":"podunaj",
     "neighbors":["hlohovec","piestany","senec","pezinok","sered"],
     "note":"krajské mesto s historickým jadrom a rozsiahlou prímestskou výstavbou"},
    {"slug":"dunajska-streda","mesto":"Dunajská Streda","lokativ":"Dunajskej Strede","kraj":"Trnavský kraj","region":"podunaj",
     "neighbors":["galanta","senec","komarno","bratislava"],
     "note":"centrum Žitného ostrova, rovinatý terén, kombinácia plynu a tuhých palív"},
    {"slug":"galanta","mesto":"Galanta","lokativ":"Galante","kraj":"Trnavský kraj","region":"podunaj",
     "neighbors":["sered","dunajska-streda","sala","senec"],
     "note":"podunajské mesto s prevahou rodinných domov a poľnohospodárskeho zázemia"},
    {"slug":"hlohovec","mesto":"Hlohovec","lokativ":"Hlohovci","kraj":"Trnavský kraj","region":"povazie",
     "neighbors":["trnava","piestany","sered","topolcany"],
     "note":"mesto v údolí Váhu so staršou murovanou zástavbou"},
    {"slug":"piestany","mesto":"Piešťany","lokativ":"Piešťanoch","kraj":"Trnavský kraj","region":"povazie",
     "neighbors":["hlohovec","trnava","nove-mesto-nad-vahom","topolcany"],
     "note":"kúpeľné mesto na Váhu s vilovou aj bytovou zástavbou"},
    {"slug":"senica","mesto":"Senica","lokativ":"Senici","kraj":"Trnavský kraj","region":"zahorie",
     "neighbors":["skalica","malacky","myjava","trnava"],
     "note":"záhorské mesto s prevahou kúrenia na drevo na okolitých kopaniciach"},
    {"slug":"skalica","mesto":"Skalica","lokativ":"Skalici","kraj":"Trnavský kraj","region":"zahorie",
     "neighbors":["senica","malacky","myjava","holic"],
     "note":"historické mesto pri moravskej hranici so staršími murovanými komínmi"},
    # Trenčiansky kraj
    {"slug":"trencin","mesto":"Trenčín","lokativ":"Trenčíne","kraj":"Trenčiansky kraj","region":"povazie",
     "neighbors":["dubnica-nad-vahom","nove-mesto-nad-vahom","banovce-nad-bebravou","ilava"],
     "note":"krajské mesto v údolí Váhu pod hradom, mix bytovej a rodinnej zástavby"},
    {"slug":"banovce-nad-bebravou","mesto":"Bánovce nad Bebravou","lokativ":"Bánovciach nad Bebravou","kraj":"Trenčiansky kraj","region":"povazie",
     "neighbors":["trencin","partizanske","topolcany","prievidza"],
     "note":"mesto na Bebrave s prevahou rodinných domov a kotlov na tuhé palivo"},
    {"slug":"ilava","mesto":"Ilava","lokativ":"Ilave","kraj":"Trenčiansky kraj","region":"povazie",
     "neighbors":["dubnica-nad-vahom","puchov","povazska-bystrica","trencin"],
     "note":"považské mesto so staršou zástavbou v údolí pod Strážovskými vrchmi"},
    {"slug":"myjava","mesto":"Myjava","lokativ":"Myjave","kraj":"Trenčiansky kraj","region":"povazie",
     "neighbors":["nove-mesto-nad-vahom","senica","trencin","skalica"],
     "note":"kopaničiarsky región s roztrúsenou zástavbou a kúrením na drevo"},
    {"slug":"nove-mesto-nad-vahom","mesto":"Nové Mesto nad Váhom","lokativ":"Novom Meste nad Váhom","kraj":"Trenčiansky kraj","region":"povazie",
     "neighbors":["trencin","piestany","myjava","banovce-nad-bebravou"],
     "note":"mesto na Váhu s murovanou aj novou zástavbou pod Považským Inovcom"},
    {"slug":"partizanske","mesto":"Partizánske","lokativ":"Partizánskom","kraj":"Trenčiansky kraj","region":"ponitrie",
     "neighbors":["topolcany","prievidza","banovce-nad-bebravou","zlate-moravce"],
     "note":"priemyselné mesto so staršou bytovou aj rodinnou zástavbou"},
    {"slug":"povazska-bystrica","mesto":"Považská Bystrica","lokativ":"Považskej Bystrici","kraj":"Trenčiansky kraj","region":"povazie",
     "neighbors":["puchov","ilava","zilina","bytca"],
     "note":"horné Považie, kotly na tuhé palivo a dlhšia vykurovacia sezóna"},
    {"slug":"prievidza","mesto":"Prievidza","lokativ":"Prievidzi","kraj":"Trenčiansky kraj","region":"ponitrie",
     "neighbors":["partizanske","banovce-nad-bebravou","topolcany","martin"],
     "note":"hornonitrianske mesto, prechod od uhlia ku kúreniu na drevo a plyn"},
    {"slug":"puchov","mesto":"Púchov","lokativ":"Púchove","kraj":"Trenčiansky kraj","region":"povazie",
     "neighbors":["povazska-bystrica","ilava","zilina","dubnica-nad-vahom"],
     "note":"považské mesto v údolí s prevahou tuhých palív v okolitých obciach"},
    {"slug":"dubnica-nad-vahom","mesto":"Dubnica nad Váhom","lokativ":"Dubnici nad Váhom","kraj":"Trenčiansky kraj","region":"povazie",
     "neighbors":["ilava","trencin","puchov","povazska-bystrica"],
     "note":"priemyselné mesto na Váhu s bytovou aj rodinnou zástavbou"},
    # Nitriansky kraj
    {"slug":"nitra","mesto":"Nitra","lokativ":"Nitre","kraj":"Nitriansky kraj","region":"ponitrie",
     "neighbors":["zlate-moravce","topolcany","sala","levice","nove-zamky"],
     "note":"krajské mesto pod Zoborom s historickou aj modernou zástavbou"},
    {"slug":"komarno","mesto":"Komárno","lokativ":"Komárne","kraj":"Nitriansky kraj","region":"podunaj",
     "neighbors":["nove-zamky","dunajska-streda","sala","levice"],
     "note":"podunajské mesto na sútoku Váhu a Dunaja, rovinatá zástavba"},
    {"slug":"levice","mesto":"Levice","lokativ":"Leviciach","kraj":"Nitriansky kraj","region":"ponitrie",
     "neighbors":["nitra","nove-zamky","zlate-moravce","krupina"],
     "note":"mesto na Pohroní s vinohradníckou aj rodinnou zástavbou"},
    {"slug":"nove-zamky","mesto":"Nové Zámky","lokativ":"Nových Zámkoch","kraj":"Nitriansky kraj","region":"podunaj",
     "neighbors":["komarno","sala","levice","nitra"],
     "note":"podunajské mesto s rovinatým terénom a staršou murovanou zástavbou"},
    {"slug":"sala","mesto":"Šaľa","lokativ":"Šali","kraj":"Nitriansky kraj","region":"podunaj",
     "neighbors":["galanta","nove-zamky","nitra","sered"],
     "note":"mesto na dolnom Váhu s prevahou rodinných domov"},
    {"slug":"topolcany","mesto":"Topoľčany","lokativ":"Topoľčanoch","kraj":"Nitriansky kraj","region":"ponitrie",
     "neighbors":["partizanske","nitra","hlohovec","banovce-nad-bebravou"],
     "note":"ponitrianske mesto s rozsiahlym vidieckym zázemím a kúrením na drevo"},
    {"slug":"zlate-moravce","mesto":"Zlaté Moravce","lokativ":"Zlatých Moravciach","kraj":"Nitriansky kraj","region":"ponitrie",
     "neighbors":["nitra","levice","partizanske","topolcany"],
     "note":"mesto pod Tribečom so staršími murovanými komínmi"},
    # Žilinský kraj
    {"slug":"zilina","mesto":"Žilina","lokativ":"Žiline","kraj":"Žilinský kraj","region":"povazie",
     "neighbors":["bytca","cadca","martin","povazska-bystrica","kysucke-nove-mesto"],
     "note":"krajské mesto na sútoku Váhu a Kysuce, mestská aj prímestská zástavba"},
    {"slug":"bytca","mesto":"Bytča","lokativ":"Bytči","kraj":"Žilinský kraj","region":"povazie",
     "neighbors":["zilina","povazska-bystrica","cadca","kysucke-nove-mesto"],
     "note":"považské mesto v údolí Váhu s prevahou rodinných domov"},
    {"slug":"cadca","mesto":"Čadca","lokativ":"Čadci","kraj":"Žilinský kraj","region":"turiec_orava_liptov",
     "neighbors":["kysucke-nove-mesto","zilina","bytca","namestovo"],
     "note":"kysucký región s tvrdými zimami a prevahou kúrenia na drevo"},
    {"slug":"kysucke-nove-mesto","mesto":"Kysucké Nové Mesto","lokativ":"Kysuckom Novom Meste","kraj":"Žilinský kraj","region":"turiec_orava_liptov",
     "neighbors":["cadca","zilina","bytca","namestovo"],
     "note":"kysucké mesto v údolí s dlhou vykurovacou sezónou"},
    {"slug":"dolny-kubin","mesto":"Dolný Kubín","lokativ":"Dolnom Kubíne","kraj":"Žilinský kraj","region":"turiec_orava_liptov",
     "neighbors":["namestovo","tvrdosin","ruzomberok","martin"],
     "note":"oravské mesto s tuhými zimami a intenzívnym kúrením na drevo"},
    {"slug":"namestovo","mesto":"Námestovo","lokativ":"Námestove","kraj":"Žilinský kraj","region":"turiec_orava_liptov",
     "neighbors":["dolny-kubin","tvrdosin","cadca","kysucke-nove-mesto"],
     "note":"hornooravské mesto pri priehrade, jedny z najtvrdších zím na Slovensku"},
    {"slug":"tvrdosin","mesto":"Tvrdošín","lokativ":"Tvrdošíne","kraj":"Žilinský kraj","region":"turiec_orava_liptov",
     "neighbors":["namestovo","dolny-kubin","liptovsky-mikulas","ruzomberok"],
     "note":"oravské mesto pod Roháčmi s dlhou a chladnou vykurovacou sezónou"},
    {"slug":"martin","mesto":"Martin","lokativ":"Martine","kraj":"Žilinský kraj","region":"turiec_orava_liptov",
     "neighbors":["turcianske-teplice","ruzomberok","zilina","dolny-kubin"],
     "note":"turčianske krajské centrum s bytovou aj rodinnou zástavbou v kotline"},
    {"slug":"turcianske-teplice","mesto":"Turčianske Teplice","lokativ":"Turčianskych Tepliciach","kraj":"Žilinský kraj","region":"turiec_orava_liptov",
     "neighbors":["martin","prievidza","banska-bystrica","ruzomberok"],
     "note":"kúpeľné mesto v Turci so staršou murovanou zástavbou"},
    {"slug":"ruzomberok","mesto":"Ružomberok","lokativ":"Ružomberku","kraj":"Žilinský kraj","region":"turiec_orava_liptov",
     "neighbors":["liptovsky-mikulas","dolny-kubin","martin","turcianske-teplice"],
     "note":"liptovské mesto na sútoku Váhu a Revúcej, tuhé zimy a kúrenie na drevo"},
    {"slug":"liptovsky-mikulas","mesto":"Liptovský Mikuláš","lokativ":"Liptovskom Mikuláši","kraj":"Žilinský kraj","region":"turiec_orava_liptov",
     "neighbors":["ruzomberok","poprad","tvrdosin","brezno"],
     "note":"naše domáce mesto v srdci Liptova — práve odtiaľto pôsobíme a poznáme miestne podmienky"},
    # Banskobystrický kraj
    {"slug":"banska-bystrica","mesto":"Banská Bystrica","lokativ":"Banskej Bystrici","kraj":"Banskobystrický kraj","region":"horehronie",
     "neighbors":["zvolen","brezno","banska-stiavnica","detva"],
     "note":"krajské mesto v kotline pod Nízkymi Tatrami, mix bytovej a rodinnej zástavby"},
    {"slug":"brezno","mesto":"Brezno","lokativ":"Brezne","kraj":"Banskobystrický kraj","region":"horehronie",
     "neighbors":["banska-bystrica","liptovsky-mikulas","poprad","detva"],
     "note":"horehronské mesto s dlhou a chladnou vykurovacou sezónou, drevo ako hlavné palivo"},
    {"slug":"zvolen","mesto":"Zvolen","lokativ":"Zvolene","kraj":"Banskobystrický kraj","region":"horehronie",
     "neighbors":["banska-bystrica","detva","krupina","banska-stiavnica"],
     "note":"mesto na sútoku Hrona a Slatiny s bytovou aj rodinnou zástavbou"},
    {"slug":"banska-stiavnica","mesto":"Banská Štiavnica","lokativ":"Banskej Štiavnici","kraj":"Banskobystrický kraj","region":"horehronie",
     "neighbors":["zvolen","krupina","zarnovica","banska-bystrica"],
     "note":"historické banské mesto s pamiatkovou zástavbou a starými murovanými komínmi"},
    {"slug":"detva","mesto":"Detva","lokativ":"Detve","kraj":"Banskobystrický kraj","region":"horehronie",
     "neighbors":["zvolen","banska-bystrica","krupina","brezno"],
     "note":"podpolianske mesto s lazníckou zástavbou a prevahou kúrenia na drevo"},
    {"slug":"krupina","mesto":"Krupina","lokativ":"Krupine","kraj":"Banskobystrický kraj","region":"gemer_novohrad",
     "neighbors":["zvolen","detva","levice","banska-stiavnica"],
     "note":"mesto na Hontu so staršou murovanou zástavbou"},
    {"slug":"zarnovica","mesto":"Žarnovica","lokativ":"Žarnovici","kraj":"Banskobystrický kraj","region":"horehronie",
     "neighbors":["banska-stiavnica","ziar-nad-hronom","zvolen","levice"],
     "note":"pohronské mesto v údolí s rodinnou zástavbou"},
    {"slug":"ziar-nad-hronom","mesto":"Žiar nad Hronom","lokativ":"Žiari nad Hronom","kraj":"Banskobystrický kraj","region":"horehronie",
     "neighbors":["zarnovica","banska-stiavnica","zvolen","banska-bystrica"],
     "note":"priemyselné mesto na Hrone s bytovou aj rodinnou zástavbou"},
    {"slug":"luc enec","mesto":"Lučenec","lokativ":"Lučenci","kraj":"Banskobystrický kraj","region":"gemer_novohrad",
     "neighbors":["velky-krtis","rimavska-sobota","detva","polt ar"],
     "note":"novohradské mesto s rovinatým okolím a staršími murovanými komínmi"},
    {"slug":"lucenec","mesto":"Lučenec","lokativ":"Lučenci","kraj":"Banskobystrický kraj","region":"gemer_novohrad",
     "neighbors":["velky-krtis","rimavska-sobota","poltar","detva"],
     "note":"novohradské mesto s rovinatým okolím a staršími murovanými komínmi"},
    {"slug":"poltar","mesto":"Poltár","lokativ":"Poltári","kraj":"Banskobystrický kraj","region":"gemer_novohrad",
     "neighbors":["lucenec","rimavska-sobota","velky-krtis","brezno"],
     "note":"novohradské mesto s vidieckou zástavbou a kúrením na drevo"},
    {"slug":"rimavska-sobota","mesto":"Rimavská Sobota","lokativ":"Rimavskej Sobote","kraj":"Banskobystrický kraj","region":"gemer_novohrad",
     "neighbors":["lucenec","poltar","revuca","roznava"],
     "note":"gemerské mesto s rovinatým okolím, časté dechtovanie starých komínov"},
    {"slug":"revuca","mesto":"Revúca","lokativ":"Revúcej","kraj":"Banskobystrický kraj","region":"gemer_novohrad",
     "neighbors":["rimavska-sobota","roznava","brezno","poltar"],
     "note":"gemerské mesto v doline so starou murovanou zástavbou a kúrením na drevo"},
    {"slug":"velky-krtis","mesto":"Veľký Krtíš","lokativ":"Veľkom Krtíši","kraj":"Banskobystrický kraj","region":"gemer_novohrad",
     "neighbors":["lucenec","krupina","levice","poltar"],
     "note":"novohradské mesto s vinohradníckou a rodinnou zástavbou"},
    # Prešovský kraj
    {"slug":"presov","mesto":"Prešov","lokativ":"Prešove","kraj":"Prešovský kraj","region":"saris",
     "neighbors":["kosice","sabinov","vranov-nad-toplou","bardejov"],
     "note":"krajské mesto Šariša s historickým jadrom a rozsiahlou sídliskovou zástavbou"},
    {"slug":"bardejov","mesto":"Bardejov","lokativ":"Bardejove","kraj":"Prešovský kraj","region":"saris",
     "neighbors":["presov","svidnik","sabinov","stropkov"],
     "note":"historické mesto so zachovaným jadrom a starými murovanými komínmi, tuhé zimy"},
    {"slug":"humenne","mesto":"Humenné","lokativ":"Humennom","kraj":"Prešovský kraj","region":"zemplin",
     "neighbors":["snina","medzilaborce","vranov-nad-toplou","stropkov"],
     "note":"zemplínske mesto na Laborci s bytovou aj rodinnou zástavbou"},
    {"slug":"kezmarok","mesto":"Kežmarok","lokativ":"Kežmarku","kraj":"Prešovský kraj","region":"spis",
     "neighbors":["poprad","stara-lubovna","levoca","spisska-nova-ves"],
     "note":"podtatranské mesto s historickým jadrom, tvrdé zimy a vysoké nároky na ťah"},
    {"slug":"levoca","mesto":"Levoča","lokativ":"Levoči","kraj":"Prešovský kraj","region":"spis",
     "neighbors":["spisska-nova-ves","kezmarok","poprad","presov"],
     "note":"historické spišské mesto s pamiatkovou zástavbou a starými komínmi"},
    {"slug":"medzilaborce","mesto":"Medzilaborce","lokativ":"Medzilaborciach","kraj":"Prešovský kraj","region":"zemplin",
     "neighbors":["humenne","snina","stropkov","svidnik"],
     "note":"severozemplínske mesto pri poľskej hranici s kúrením na drevo"},
    {"slug":"poprad","mesto":"Poprad","lokativ":"Poprade","kraj":"Prešovský kraj","region":"spis",
     "neighbors":["kezmarok","liptovsky-mikulas","levoca","spisska-nova-ves"],
     "note":"brána do Vysokých Tatier s tvrdými zimami a vysokými nárokmi na komín"},
    {"slug":"sabinov","mesto":"Sabinov","lokativ":"Sabinove","kraj":"Prešovský kraj","region":"saris",
     "neighbors":["presov","bardejov","stara-lubovna","kezmarok"],
     "note":"šarišské mesto v doline Torysy so staršou murovanou zástavbou"},
    {"slug":"snina","mesto":"Snina","lokativ":"Snine","kraj":"Prešovský kraj","region":"zemplin",
     "neighbors":["humenne","medzilaborce","sobrance","vranov-nad-toplou"],
     "note":"mesto pod Vihorlatom pri ukrajinskej hranici, prevaha kúrenia na drevo"},
    {"slug":"stara-lubovna","mesto":"Stará Ľubovňa","lokativ":"Starej Ľubovni","kraj":"Prešovský kraj","region":"spis",
     "neighbors":["kezmarok","sabinov","bardejov","poprad"],
     "note":"spišské mesto na severe s tuhými zimami a kúrením na drevo"},
    {"slug":"stropkov","mesto":"Stropkov","lokativ":"Stropkove","kraj":"Prešovský kraj","region":"saris",
     "neighbors":["svidnik","bardejov","humenne","medzilaborce"],
     "note":"mesto na Ondave s vidieckym zázemím a kúrením na tuhé palivo"},
    {"slug":"svidnik","mesto":"Svidník","lokativ":"Svidníku","kraj":"Prešovský kraj","region":"saris",
     "neighbors":["bardejov","stropkov","medzilaborce","presov"],
     "note":"severošarišské mesto pri poľskej hranici, dlhá vykurovacia sezóna"},
    {"slug":"vranov-nad-toplou","mesto":"Vranov nad Topľou","lokativ":"Vranove nad Topľou","kraj":"Prešovský kraj","region":"zemplin",
     "neighbors":["humenne","presov","snina","michalovce"],
     "note":"zemplínske mesto na Topli s rodinnou zástavbou a kotlami na tuhé palivo"},
    # Košický kraj
    {"slug":"kosice","mesto":"Košice","lokativ":"Košiciach","kraj":"Košický kraj","region":"kosice_okolie",
     "neighbors":["presov","roznava","trebisov","michalovce","spisska-nova-ves"],
     "note":"druhé najväčšie mesto SR s rozsiahlymi sídliskami aj rodinnou zástavbou na okraji"},
    {"slug":"gelnica","mesto":"Gelnica","lokativ":"Gelnici","kraj":"Košický kraj","region":"spis",
     "neighbors":["spisska-nova-ves","kosice","roznava","levoca"],
     "note":"banské mesto v Hnileckej doline s kúrením na drevo a tuhými zimami"},
    {"slug":"michalovce","mesto":"Michalovce","lokativ":"Michalovciach","kraj":"Košický kraj","region":"zemplin",
     "neighbors":["trebisov","sobrance","vranov-nad-toplou","kosice"],
     "note":"zemplínske mesto pri Zemplínskej šírave s rovinatou zástavbou"},
    {"slug":"roznava","mesto":"Rožňava","lokativ":"Rožňave","kraj":"Košický kraj","region":"gemer_novohrad",
     "neighbors":["revuca","kosice","rimavska-sobota","spisska-nova-ves"],
     "note":"gemerské banské mesto v kotline so staršou murovanou zástavbou"},
    {"slug":"sobrance","mesto":"Sobrance","lokativ":"Sobranciach","kraj":"Košický kraj","region":"zemplin",
     "neighbors":["michalovce","snina","trebisov","humenne"],
     "note":"východozemplínske mesto pri ukrajinskej hranici, vidiecka zástavba"},
    {"slug":"spisska-nova-ves","mesto":"Spišská Nová Ves","lokativ":"Spišskej Novej Vsi","kraj":"Košický kraj","region":"spis",
     "neighbors":["levoca","gelnica","poprad","kosice"],
     "note":"spišské mesto s najdlhším námestím na Slovensku, tvrdé zimy"},
    {"slug":"trebisov","mesto":"Trebišov","lokativ":"Trebišove","kraj":"Košický kraj","region":"zemplin",
     "neighbors":["michalovce","kosice","sobrance","vranov-nad-toplou"],
     "note":"mesto na Východoslovenskej nížine s rovinatou rodinnou zástavbou"},
]

# doplnenie zvyšných okresných miest pre úplné pokrytie
CITIES += [
    {"slug":"sered","mesto":"Sereď","lokativ":"Seredi","kraj":"Trnavský kraj","region":"podunaj",
     "neighbors":["galanta","trnava","hlohovec","sala"],
     "note":"mesto na dolnom Váhu s rodinnou zástavbou a prímestskou výstavbou"},
    {"slug":"holic","mesto":"Holíč","lokativ":"Holíči","kraj":"Trnavský kraj","region":"zahorie",
     "neighbors":["skalica","senica","malacky","myjava"],
     "note":"záhorské mesto pri moravskej hranici so staršou murovanou zástavbou"},
]

# dedup podľa slugu (cities.py má jednu chybnú duplicitu s medzerou)
_seen=set(); _out=[]
for c in CITIES:
    s=c["slug"].strip()
    if not s or " " in s or not c.get("mesto"):  # vyhoď chybné/prázdne záznamy
        continue
    if s in _seen:
        continue
    _seen.add(s); c["slug"]=s; _out.append(c)
CITIES=_out

# vyčisti neighbors -> len existujúce slugy, max 5
_valid={c["slug"] for c in CITIES}
for c in CITIES:
    c["neighbors"]=[n for n in c["neighbors"] if n in _valid][:5]
